version: '3'


volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  front-tier:
  back-tier:


services:
  simple-mvc:
    build: ./SimpleMVC/.
    ports:
     - "5000:80"
     - "5001:443"
    networks:
      - front-tier
      - back-tier
    restart: always

  prometheus:
    image: prom/prometheus:v2.8.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - simple-mvc
    networks:
      - back-tier
    restart: always

  grafana:
    image: grafana/grafana:6.0.1
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - back-tier
    restart: always