version: '3'


volumes:
  prometheus_data: {}
  grafana_data: {}
  influxdb_data: {}

networks:
  front-tier:
  back-tier:

services:
  simple-mvc:
    build: ./SimpleMVC/.
    ports:
     - "80:80"
     - "443:443"
    networks:
      - front-tier
      - back-tier
    restart: always

  prometheus:
    image: prom/prometheus:v2.8.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    depends_on:
      - simple-mvc
    networks:
      - back-tier
    restart: always

  promgateway:
    image: prom/pushgateway:latest
    restart: always
    ports:
      - 9091:9091
    networks:
      - back-tier
    restart: always

  influxdb:
    image: influxdb:alpine
    ports:
      - 8086:8086
    networks:
      - back-tier
    volumes:
      - influxdb_data:/var/lib/influxdb

  blackbox-exporter:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    volumes:
      - "./blackbox:/config"
    command: 
      - '--config.file=/config/blackbox.yml'
    networks:
      - back-tier
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:6.0.1
    user: "472"
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,vonage-status-panel,grafana-piechart-panel
    networks:
      - back-tier
    restart: always